package GUI;

import java.awt.*;

/**
 *
 * @author Thomas
 */
public class MessagerieGUI extends javax.swing.JPanel {

    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextPane jTextPane1;
    private String debutTexte;
    private String finTexte;
    // End of variables declaration

    /**
     * Creates new form MessagerieGUI
     */
    public MessagerieGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(102, 102, 102));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane6.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane6.setBorder(null);
        jScrollPane6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextPane1.setEditable(false);
        jTextPane1.setFocusable(false);
        jTextPane1.setBackground(new java.awt.Color(102, 102, 102));
        jTextPane1.setBorder(null);
        jTextPane1.setContentType("text/html"); // NOI18N
        debutTexte="<html>\r\n<head>\r\n\r\n</head>\r\n<body bgcolor=\"#FFFFFF\">\r\n<p style=\"margin-top: 1 ; margin-left: 5\">\r<font size=\"+1\">Messagerie :<br>\n";
        finTexte="</font></p>\n</body>\n</html>\n";
        jTextPane1.setText(debutTexte+finTexte);

        jScrollPane6.setViewportView(jTextPane1);

        jPanel3.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel3);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>


}

