package GUI;

import Game.Context;
import Game.Monster;
import Game.Player;

/**
 *
 * @author Thomas
 */
public class PrincipalGUI extends javax.swing.JFrame {


    // Variables declaration - do not modify
    private ActionsGUI actionsGUI1;
    private InformationsGUI informationsGUI1;
    private javax.swing.JPanel jPanel1;
    private static Context context;
    // End of variables declaration

    /**
     * Creates new form NewJFrame1
     */
    public PrincipalGUI(Context context) {
        this.context=context;
        initComponents();
    }

    public ActionsGUI getActionsGUI1() {
        return actionsGUI1;
    }

    public void setActionsGUI1(ActionsGUI actionsGUI1) {
        this.actionsGUI1 = actionsGUI1;
    }

    public InformationsGUI getInformationsGUI1() {
        return informationsGUI1;
    }

    public void setInformationsGUI1(InformationsGUI informationsGUI1) {
        this.informationsGUI1 = informationsGUI1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        informationsGUI1 = new InformationsGUI(context);
        actionsGUI1 = new ActionsGUI();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(informationsGUI1, java.awt.BorderLayout.CENTER);
        jPanel1.add(actionsGUI1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        Context context=new Context();
        context.addPlayer(new Player("Antonio", 10,1,1,1,10));
        context.addMonster(new Monster("0", "Chupacabra", 10,1,1,1,10));
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalGUI(context).setVisible(true);
            }
        });
    }
}
